export enum InfraConfigEnum {
  ONBOARDING_COMPLETED = 'ONBOARDING_COMPLETED',
  ONBOARDING_RECOVERY_TOKEN = 'ONBOARDING_RECOVERY_TOKEN',

  JWT_SECRET = 'JWT_SECRET',
  SESSION_SECRET = 'SESSION_SECRET',
  SESSION_COOKIE_NAME = 'SESSION_COOKIE_NAME',
  TOKEN_SALT_COMPLEXITY = 'TOKEN_SALT_COMPLEXITY',
  MAGIC_LINK_TOKEN_VALIDITY = 'MAGIC_LINK_TOKEN_VALIDITY',
  REFRESH_TOKEN_VALIDITY = 'REFRESH_TOKEN_VALIDITY',
  ACCESS_TOKEN_VALIDITY = 'ACCESS_TOKEN_VALIDITY',
  ALLOW_SECURE_COOKIES = 'ALLOW_SECURE_COOKIES',

  RATE_LIMIT_TTL = 'RATE_LIMIT_TTL',
  RATE_LIMIT_MAX = 'RATE_LIMIT_MAX',

  MAILER_SMTP_ENABLE = 'MAILER_SMTP_ENABLE',
  MAILER_USE_CUSTOM_CONFIGS = 'MAILER_USE_CUSTOM_CONFIGS',
  MAILER_SMTP_URL = 'MAILER_SMTP_URL',
  MAILER_ADDRESS_FROM = 'MAILER_ADDRESS_FROM',

  MAILER_SMTP_HOST = 'MAILER_SMTP_HOST',
  MAILER_SMTP_PORT = 'MAILER_SMTP_PORT',
  MAILER_SMTP_SECURE = 'MAILER_SMTP_SECURE',
  MAILER_SMTP_USER = 'MAILER_SMTP_USER',
  MAILER_SMTP_PASSWORD = 'MAILER_SMTP_PASSWORD',
  MAILER_TLS_REJECT_UNAUTHORIZED = 'MAILER_TLS_REJECT_UNAUTHORIZED',
  MAILER_SMTP_IGNORE_TLS = 'MAILER_SMTP_IGNORE_TLS',

  MAILER_SMTP_AUTH_TYPE = 'MAILER_SMTP_AUTH_TYPE',
  MAILER_SMTP_OAUTH2_USER = 'MAILER_SMTP_OAUTH2_USER',
  MAILER_SMTP_OAUTH2_CLIENT_ID = 'MAILER_SMTP_OAUTH2_CLIENT_ID',
  MAILER_SMTP_OAUTH2_CLIENT_SECRET = 'MAILER_SMTP_OAUTH2_CLIENT_SECRET',
  MAILER_SMTP_OAUTH2_REFRESH_TOKEN = 'MAILER_SMTP_OAUTH2_REFRESH_TOKEN',
  MAILER_SMTP_OAUTH2_ACCESS_URL = 'MAILER_SMTP_OAUTH2_ACCESS_URL',

  GOOGLE_CLIENT_ID = 'GOOGLE_CLIENT_ID',
  GOOGLE_CLIENT_SECRET = 'GOOGLE_CLIENT_SECRET',
  GOOGLE_CALLBACK_URL = 'GOOGLE_CALLBACK_URL',
  GOOGLE_SCOPE = 'GOOGLE_SCOPE',

  GITHUB_CLIENT_ID = 'GITHUB_CLIENT_ID',
  GITHUB_CLIENT_SECRET = 'GITHUB_CLIENT_SECRET',
  GITHUB_CALLBACK_URL = 'GITHUB_CALLBACK_URL',
  GITHUB_SCOPE = 'GITHUB_SCOPE',

  MICROSOFT_CLIENT_ID = 'MICROSOFT_CLIENT_ID',
  MICROSOFT_CLIENT_SECRET = 'MICROSOFT_CLIENT_SECRET',
  MICROSOFT_CALLBACK_URL = 'MICROSOFT_CALLBACK_URL',
  MICROSOFT_SCOPE = 'MICROSOFT_SCOPE',
  MICROSOFT_TENANT = 'MICROSOFT_TENANT',

  VITE_ALLOWED_AUTH_PROVIDERS = 'VITE_ALLOWED_AUTH_PROVIDERS',

  PROXY_APP_URL = 'PROXY_APP_URL',

  ALLOW_ANALYTICS_COLLECTION = 'ALLOW_ANALYTICS_COLLECTION',
  ANALYTICS_USER_ID = 'ANALYTICS_USER_ID',
  IS_FIRST_TIME_INFRA_SETUP = 'IS_FIRST_TIME_INFRA_SETUP',

  USER_HISTORY_STORE_ENABLED = 'USER_HISTORY_STORE_ENABLED',

  MOCK_SERVER_WILDCARD_DOMAIN = 'MOCK_SERVER_WILDCARD_DOMAIN',

  // AI / LLM provider configuration (Azure AI Foundry).
  // These are excluded from the generic `updateInfraConfigs` mutation and are
  // written through `updateAIConfigs` instead, so saving them does not restart
  // the server. See InfraConfigService.EXCLUDE_FROM_UPDATE_CONFIGS.
  AI_ENABLED = 'AI_ENABLED',
  AI_PROVIDER = 'AI_PROVIDER',

  AI_AZURE_FOUNDRY_RESOURCE = 'AI_AZURE_FOUNDRY_RESOURCE',
  AI_AZURE_FOUNDRY_API_KEY = 'AI_AZURE_FOUNDRY_API_KEY',
  AI_AZURE_FOUNDRY_MODEL = 'AI_AZURE_FOUNDRY_MODEL',

  AI_AZURE_OPENAI_ENDPOINT = 'AI_AZURE_OPENAI_ENDPOINT',
  AI_AZURE_OPENAI_API_KEY = 'AI_AZURE_OPENAI_API_KEY',
  AI_AZURE_OPENAI_DEPLOYMENT = 'AI_AZURE_OPENAI_DEPLOYMENT',
  AI_AZURE_OPENAI_API_VERSION = 'AI_AZURE_OPENAI_API_VERSION',

  AI_MAX_OUTPUT_TOKENS = 'AI_MAX_OUTPUT_TOKENS',
  AI_MAX_TOOL_ITERATIONS = 'AI_MAX_TOOL_ITERATIONS',
  AI_ENABLE_THINKING = 'AI_ENABLE_THINKING',

  AI_MCP_ENABLED = 'AI_MCP_ENABLED',

  // Outbound request execution used by the agent's run-request tools.
  AGENT_REQUEST_EXECUTION_ENABLED = 'AGENT_REQUEST_EXECUTION_ENABLED',
  AGENT_REQUEST_ALLOWED_HOSTS = 'AGENT_REQUEST_ALLOWED_HOSTS',
  AGENT_REQUEST_TIMEOUT_MS = 'AGENT_REQUEST_TIMEOUT_MS',
  AGENT_REQUEST_MAX_RESPONSE_BYTES = 'AGENT_REQUEST_MAX_RESPONSE_BYTES',
}

/** LLM vendor backing the AI features. Both are served by Azure AI Foundry. */
export enum AIProvider {
  AZURE_FOUNDRY_ANTHROPIC = 'AZURE_FOUNDRY_ANTHROPIC',
  AZURE_OPENAI = 'AZURE_OPENAI',
}

/** Every AI/agent config key, used to gate `updateAIConfigs`. */
export const AI_CONFIG_KEYS = [
  InfraConfigEnum.AI_ENABLED,
  InfraConfigEnum.AI_PROVIDER,
  InfraConfigEnum.AI_AZURE_FOUNDRY_RESOURCE,
  InfraConfigEnum.AI_AZURE_FOUNDRY_API_KEY,
  InfraConfigEnum.AI_AZURE_FOUNDRY_MODEL,
  InfraConfigEnum.AI_AZURE_OPENAI_ENDPOINT,
  InfraConfigEnum.AI_AZURE_OPENAI_API_KEY,
  InfraConfigEnum.AI_AZURE_OPENAI_DEPLOYMENT,
  InfraConfigEnum.AI_AZURE_OPENAI_API_VERSION,
  InfraConfigEnum.AI_MAX_OUTPUT_TOKENS,
  InfraConfigEnum.AI_MAX_TOOL_ITERATIONS,
  InfraConfigEnum.AI_ENABLE_THINKING,
  InfraConfigEnum.AI_MCP_ENABLED,
  InfraConfigEnum.AGENT_REQUEST_EXECUTION_ENABLED,
  InfraConfigEnum.AGENT_REQUEST_ALLOWED_HOSTS,
  InfraConfigEnum.AGENT_REQUEST_TIMEOUT_MS,
  InfraConfigEnum.AGENT_REQUEST_MAX_RESPONSE_BYTES,
] as const;

/** Secret AI config keys, stored encrypted at rest. */
export const AI_SECRET_CONFIG_KEYS: InfraConfigEnum[] = [
  InfraConfigEnum.AI_AZURE_FOUNDRY_API_KEY,
  InfraConfigEnum.AI_AZURE_OPENAI_API_KEY,
];

/**
 * Placeholder the admin UI renders in place of a stored secret. An incoming
 * value equal to this means "leave the existing value unchanged".
 */
export const AI_SECRET_MASK = '\u2022\u2022\u2022\u2022\u2022\u2022\u2022\u2022';
